app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
use Yajra\Datatables\Datatables;

use App\Cuenta;

Route::group(['middleware' => 'auth'],function(){
	Route::group(['middleware'=>'activo'],function(){

		Route::get('/', function () {
			if (Auth::user()->rol_id == 5) {
				return redirect()->route('supervisor.index');		
			}
			else{
				return redirect()->route('cuentas_tesoreria.index');
			}
		});

		Route::group(['middleware'=>'Admin_app'],function(){
			Route::get('mantenimiento', function() {
				$li='mantenimiento';
				return view('dashboard.mantenimiento.index')->with('li',$li);		
			});
			Route::get('roles/listar', 'RolesController@listar');
			Route::get('roles/getRoles', 'RolesController@getRoles');
			Route::resource('roles', 'RolesController');
			Route::get('usuarios/listar', 'UsuariosController@listar');
			Route::post('usuarios', ['as' =>'usuarios.store' , 'uses' => 'UsuariosController@store']);
			Route::delete('usuarios/{usuario}', ['as' =>'usuarios.destroy' , 'uses' => 'UsuariosController@destroy']);
		});

		Route::get('usuarios/{usuario}', ['as' =>'usuarios.show' , 'uses' => 'UsuariosController@show']);
		Route::put('usuarios/{usuario}', ['as'=>'usuarios.update' ,'uses' =>'UsuariosController@update']);

		Route::group(['middleware'=>'user'],function(){
			Route::get('cuentas_tesoreria/listar', 'CuentasTesoreriaController@listar');
			Route::put('cuentas_tesoreria/aprobar', 'CuentasTesoreriaController@aprobar');
			Route::put('cuentas_tesoreria/rechazar', 'CuentasTesoreriaController@rechazar');
			Route::get('cuentas_tesoreria/por_pagar', ['as' =>'cuentas_tesoreria.por_pagar' , 'uses' => 'CuentasTesoreriaController@por_pagar']);
			Route::put('cuentas_tesoreria/guardar_pago', ['as' =>'cuentas_tesoreria.guardar_pago' , 'uses' => 'CuentasTesoreriaController@guardar_pago']);
			Route::resource('cuentas_tesoreria', 'CuentasTesoreriaController');
		});

		Route::group(['middleware'=>'supervisor'],function(){
			Route::put('supervisor/procesado', ['as' =>'supervisor.procesado' , 'uses' => 'SupController@procesado']);			
			Route::get('supervisor/procesar',['as' =>'supervisor.procesar' , 'uses' => 'SupController@procesar']);
			Route::get('supervisor/listar', ['as' =>'supervisor.listar' , 'uses' => 'SupController@listar']);
			Route::resource('supervisor', 'SupController');
		});

		Route::get('/cerradas', function () {
			if (Auth::user()->rol_id == 5 || Auth::user()->rol_id == 2) {
				$cuentas=Cuenta::where('estatus','RECHAZADO')->orWhere('estatus','PAGADO')->get();
				$cuentas->each(function($cuentas){
	                $cuentas->area=$cuentas->usuario->nombre;
	                if ($cuentas->fecha_tope != null) {
	                    $cuentas->fecha_tope = date('d-m-Y', strtotime($cuentas->fecha_tope));
	                }
	               return $cuentas;
	            });
				return view('dashboard.cerradas.cerradas')->with('li','cerradas')->with('cuentas',$cuentas);		
			}
			else{
        		Flash::error("NO ESTA AUTORIZADO PARA INGRESAR A ESTA SECCIÓN");
				return redirect()->route('cuentas_tesoreria.index');
			}
		});
		Route::get('/cerradas/listar', function() {
			if (Auth::user()->rol_id == 5 || Auth::user()->rol_id == 2) {
		        try {
			    	$cuentas=Cuenta::where('estatus','RECHAZADO')->orWhere('estatus','PAGADO')->get();
					$cuentas->each(function($cuentas){
		                $cuentas->area=$cuentas->usuario->nombre;
		                if ($cuentas->fecha_tope != null) {
		                    $cuentas->fecha_tope = date('d-m-Y', strtotime($cuentas->fecha_tope));
		                }
		               return $cuentas;
		            });
		            return Datatables::of($cuentas)->make(true);

		        } catch (\Exception $e) {
		            Log::error('Ha ocurrido un error en CuentasTesoreriaController: '.$e->getMessage().', Linea: '.$e->getLine());
		            return Datatables::of([])->make(true);
		        }				
			}
			else{
				Flash::error("NO ESTA AUTORIZADO PARA INGRESAR A ESTA SECCIÓN");
				return redirect()->route('cuentas_tesoreria.index');		
			}

		});

	});

});



Route::auth();

resources/views/dashboard/Depto/cuenta_modal.blade.php
<!-- Modal -->
<div class="modal fade" id="modal-cuenta" data-keyboard="false" data-backdrop="static">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content box">
      <div class="modal-header text-center">
        {!! Form::open(['id'=>'form-cuenta']) !!}
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">  </h4>
      </div>
      <div class="modal-body">
        {!! Form::hidden('token', csrf_token(), ['id'=>'token']) !!}
        {!! Form::hidden('id', null, ['id'=>'cuenta_id']) !!} 
        @if(Auth::user()->rol_id == 2) 
          <div class="form-group" id="field-area">
            {!! Form::label('area', 'Area:') !!}
            {!! Form::select('area', $areas, null, ['id' => 'area', 'class' => 'form-control', 'required' => 'required', 'placeholder'=>'Seleccione']) !!}
            <span><strong class="text-danger msj-error"></strong></span>
          </div>
        @else
            {!! Form::hidden('area', null, ['id'=>'area']) !!} 
        @endif        
        <div class="form-group" id="field-semana">
          {!! Form::label('semana', 'Semana del:') !!}
          {!! Form::text('semana', null, ['id' => 'semana','class' => 'form-control col-sm-4', 'required' => 'required', 'readonly']) !!}
          <small class="text-danger">{{ $errors->first('semana') }}</small>
        </div>
        <div class="form-group{{ $errors->has('beneficiario') ? ' has-error' : '' }}" id="field-beneficiario">
            {!! Form::label('beneficiario', 'Beneficiario:') !!}
            {!! Form::text('beneficiario', null, ['id'=>'beneficiario','class' => 'form-control', 'required' => 'required']) !!}
            <small class="text-danger">{{ $errors->first('beneficiario') }}</small>
        </div>
        <div class="form-group{{ $errors->has('concepto') ? ' has-error' : '' }}"  id="field-concepto">
            {!! Form::label('concepto', 'Concepto:') !!}
            {!! Form::text('concepto', null, ['id'=>'concepto','class' => 'form-control', 'required' => 'required']) !!}
            <small class="text-danger">{{ $errors->first('concepto') }}</small>
        </div>
        <div class="form-group{{ $errors->has('justificacion') ? ' has-error' : '' }}"  id="field-justificacion">
            {!! Form::label('justificacion', 'justificación:') !!}
            {!! Form::text('justificacion', null, ['id'=>'justificacion','class' => 'form-control', 'required' => 'required']) !!}
            <small class="text-danger">{{ $errors->first('justificacion') }}</small>
        </div>
        <div class="form-group{{ $errors->has('monto') ? ' has-error' : '' }}" id="field-monto">
            {!! Form::label('monto', 'Monto:') !!}
            <input type="text" class="form-control numero" placeholder="Monto de la Operación" required="true" name="monto[]" id="monto" name="monto" value="null" dir="rtl">
            <small class="text-danger">{{ $errors->first('monto') }}</small>
        </div>
        <div class="form-group{{ $errors->has('fecha_tope') ? ' has-error' : '' }}">
            {!! Form::label('fecha_tope', 'Fecha tope de pago:') !!}
            {!! Form::date('fecha_tope', null, ['id'=>'fecha_tope','class' => 'form-control', 'required' => 'required']) !!}
            <small class="text-danger">{{ $errors->first('fecha_tope') }}</small>
        </div>
        <div class="form-group{{ $errors->has('nro_orden') ? ' has-error' : '' }}">
            {!! Form::label('nro_orden', 'Nro. de Orde de Compra (Profit):') !!}
            {!! Form::text('nro_orden', null, ['id'=>'nro_orden','class' => 'form-control', 'placeholder'=>'---','onkeypress'=>'return soloNumeros(event)']) !!}
            <small class="text-danger">{{ $errors->first('nro_orden') }}</small>
        </div>
        <div class="form-group{{ $errors->has('nro_factura') ? ' has-error' : '' }}">
            {!! Form::label('nro_factura', 'Nro. de Factura (Profit):') !!}
            {!! Form::text('nro_factura', null, ['id'=>'nro_factura','class' => 'form-control', 'placeholder'=>'---','onkeypress'=>'return soloNumeros(event)']) !!}
            <small class="text-danger">{{ $errors->first('nro_factura') }}</small>
        </div>
      </div>

      <div class="modal-footer">
        <div >
          <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cerrar</button>
          <button type="button" id="guardar-cuenta" class="btn btn-success pull-right" data-loading-text="Guardando..." autocomplete="off">Guardar</button>
        </div>      
      </div>
      {!! Form::close() !!}
    </div>
  </div>
</div>

resources/views/dashboard/Depto/index.blade.php
@extends('templates.master')

@section('css')

<!-- DataTables -->  
<link rel="stylesheet" type="text/css" href="{{asset('public/plugins/datatables/dataTables.bootstrap.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('public/plugins/datatables/prueba/buttons.dataTables.min.css')}}">

@endsection

@section('titulo_modulo', Auth::user()->nombre.' - Bienvenid@')

@section('contenido')
<div class="row" >

  <div class="col-md-12">
    <div class="box box-success">
      <div class="box-body">
          <a class="btn btn-default" href="{{route('cuentas_tesoreria.create')}} ">
            <span class="text-success"><i class="fa fa-plus"></i>Agregar Cuentas</span>
          </a>
          <br /><br />
          <table id="example1" class="table table-bordered table-striped " style="text-align: center; font-size: smaller;">
            <thead>
              <tr>
                <th>ID</th>
                <th style="text-align: center;">BENEFICIARIO</th>
                <th style="text-align: center;">CONCEPTO</th>
                <th style="text-align: center;">JUSTIFICACIÓN</th>
                <th style="text-align: center;">SEMANA DEL</th>
                <th style="text-align: center;">FECHA TOPE</th>
                <th style="text-align: center;">NRO. ORDEN DE COMPRA</th>
                <th style="text-align: center;">NRO. FACTURA</th>
                <th style="text-align: center;">ESTATUS</th>
                <th style="text-align: center;">OBSERVACIÓN</th>
                <th style="text-align: center;">MONTO PROGRAMADO</th>
                <th style="text-align: center;">MONTO PAGADO</th>
                <th style="text-align: center;">VARIACIÓN</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              @foreach($cuentas as $cuenta)
              @if($cuenta->departamento_id == Auth::user()->id)
              <tr>
                <td>{{ $cuenta->id }}</td>
                <td>{{ $cuenta->beneficiario}}</td>
                <td>{{ $cuenta->concepto }}</td>
                <td>{{ $cuenta->justificacion }}</td>
                <td>{{ $cuenta->semana }}</td>
                <td>{{ $cuenta->fecha_tope }}</td>
                <td>{{ $cuenta->nro_orden }}</td>
                <td>{{ $cuenta->nro_factura }}</td>
                  @if($cuenta->estatus=='POR APROBAR' || $cuenta->estatus=='POR PRE-APROBAR' ) 
                    <td class="text-danger">
                      {{ $cuenta->estatus }}
                    </td>
                  @elseif ($cuenta->estatus=='APROBADO' || $cuenta->estatus=='PRE-APROBADO')
                    <td class="text-info">
                      {{ $cuenta->estatus }}
                    </td>
                  @elseif ($cuenta->estatus=='PAGADO')
                    <td class="text-success" >
                      {{ $cuenta->estatus }}  
                    </td>
                  @elseif ($cuenta->estatus=='RECHAZADO')
                    <td class="text-muted" >
                      {{ $cuenta->estatus }}</br>
                    </td>                      
                  @endif
                <td>{{ $cuenta->observacion }}</td>
                <td>{{ $cuenta->monto_programado }}</td>
                <td>{{ $cuenta->monto_pagado }}</td>
                <td>{{ $cuenta->variacion }}</td>
                <td>
                  @if(  ( Auth::user()->rol_id == 4 && $cuenta->estatus == 'POR PRE-APROBAR' && $editable_especial=='SI') || ((($esta_semana==$cuenta->semana  && $editable=='SI')|| $semana2==$cuenta->semana || $semana3==$cuenta->semana || $semana4==$cuenta->semana ) && $cuenta->estatus == 'POR APROBAR' ) ) 
                    <div class="btn-group" style="width: 50px">
                      <button type="button" class="btn btn-warning btn-xs" title="Editar" OnClick="showCuenta({{ $cuenta->id }})">
                        <i class="fa fa-edit"></i>
                      </button>
                      <button type="button" class="btn btn-danger btn-xs"title="Eliminar" style="margin-left:2.5px;" OnClick="deleteCuenta({{ $cuenta->id }})">
                        <i class="fa fa-remove"></i>
                      </button>
                    </div>
                  @endif
                </td>
              </tr>
              @endif
              @endforeach
            </tbody>
            <tfoot>
              <tr>
                <th>ID</th>
                <th style="text-align: center;">BENEFICIARIO</th>
                <th style="text-align: center;">CONCEPTO</th>
                <th style="text-align: center;">JUSTIFICACIÓN</th>
                <th style="text-align: center;">SEMANA DEL</th>
                <th style="text-align: center;">FECHA TOPE</th>
                <th style="text-align: center;">NRO. ORDEN DE COMPRA</th>
                <th style="text-align: center;">NRO. FACTURA</th>
                <th style="text-align: center;">ESTATUS</th>
                <th style="text-align: center;">OBSERVACIÓN</th>
                <th style="text-align: center;">MONTO PROGRAMADO</th>
                <th style="text-align: center;">MONTO PAGADO</th>
                <th style="text-align: center;">VARIACIÓN</th>
                <th></th>
              </tr>
            </tfoot>
          </table>
        </table>
        
      </div><!-- /.box-body -->
  </div>
</div>
@include('dashboard.Depto.cuenta_modal')  
@endsection

@section('js')
<!-- DataTables -->
<script src="{{asset('public/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/prueba/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/prueba/jszip.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/prueba/buttons.html5.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/prueba/dataTables.colReorder.min.js')}}"></script>

<script type="text/javascript" src="{{asset('public/js/departamentos.js')}}"></script>

<script type="text/javascript">
$(".numero").on({
  "focus": function(event) {
    $(event.target).select();
  },
  "keyup": function(event) {
    $(event.target).val(function(index, value) {
      return value.replace(/\D/g, "")
        .replace(/([0-9])([0-9]{2})$/, '$1,$2')
        .replace(/\B(?=(\d{3})+(?!\d)\.?)/g, ".");
    });
  }
});

function soloNumeros(e){
  key = e.keyCode || e.which;
  tecla = String.fromCharCode(key).toLowerCase();
  letras = "1234567890";
  especiales = "8-37-39-46";

  tecla_especial = false
  for(var i in especiales){
    if(key == especiales[i]){
      tecla_especial = true;
      break;
    }
  }

  if(letras.indexOf(tecla)==-1 && !tecla_especial){
    return false;
  }
}

</script>

@endsection

resources/views/dashboard/Depto/pago.blade.php
@extends('templates.master')

@section('css')
	<link rel="stylesheet" type="text/css" href="{{asset('public/plugins/datatables/dataTables.bootstrap.css')}}">

@endsection

@section('titulo_modulo','Realizar pago')

@section('contenido')
<div class="row" >

  <div class="col-md-12">
    <div class="box box-success">
      <div class="box-body">
          <div class="col-md-12">
            {!! Form::open(['method' => 'PUT', 'route' => 'cuentas_tesoreria.guardar_pago', 'class' => 'form-horizontal']) !!}
            <table id="myTable" class=" table order-list text-center">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>AREA</th>
                    	<th>BENEFICIARIO</th>
                        <th>CONCEPTO</th>
                        <th>SEMANA</th>
                        <th>MONTO PROGRAMADO</th>
                        <th>MONTO A PAGAR</th>
                    </tr>
                </thead>
                <tbody>
                	@foreach($cuentas as $cuenta)
                    <tr>
                        <td >{{ $cuenta->id}} </td>
                        <td >{{ $cuenta->usuario->nombre}} </td>
                        <td >{{ $cuenta->beneficiario}}</td>
                        <td >{{ $cuenta->concepto }}</td>
                        <td >{{ $cuenta->semana }}</td>
                        <td >{{ number_format($cuenta->monto_programado,2,',','.') }}</td>
                        <td>
                        	{!! Form::hidden('id[]', $cuenta->id) !!}
                          <input type="text" class="form-control numero" placeholder="----" required="true" name="monto[]" dir="rtl" onkeypress="return soloNumeros(event)">
                        </td>
                    </tr>
					@endforeach
				</tbody>
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>AREA</th>
                        <th>BENEFICIARIO</th>
                        <th>CONCEPTO</th>
                        <th>SEMANA</th>
                        <th></th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
            <div class="col-md-12">
                <br />
                  {!! Form::reset("Resetear", ['class' => 'btn btn-warning']) !!} 
                  <a href="{{ URL::previous() }}" class="btn btn-info">Cancelar</a>
                  <input type="submit" value="Guardar" class='btn btn-success pull-right' onclick="return confirm('¿Está seguro que quiere guardar estos registros? Nota: No se podrá modificar ni eliminar una vez guardados.');" >
            </div>
            {!! Form::close() !!}
          </div>
      </div>
</div>
  
@endsection

@section('js')
<!-- DataTables -->
<script src="{{asset('public/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/dataTables.bootstrap.min.js')}}"></script>

<script type="text/javascript">
$('#myTable').DataTable({
    language: leng,
    order: [[ 0, "desc" ]],
    "autoWidth": true,
    "columnDefs": [{ "orderable": false, "targets": [4] }],
    initComplete: function () {
      this.api().columns([0,1,2,4]).every( function () {
          var column = this;
          var select = $('<select><option value=""></option></select>')
              .appendTo( $(column.footer()).empty() )
              .on( 'change', function () {
                  var val = $.fn.dataTable.util.escapeRegex(
                      $(this).val()
                  );

                  column
                      .search( val ? '^'+val+'$' : '', true, false )
                      .draw();
              } );

          column.data().unique().sort().each( function ( d, j ) {
              select.append( '<option value="'+d+'">'+d+'</option>' )
          } );
      } );
    }
});

$(".numero").on({
  "focus": function(event) {
    $(event.target).select();
  },
  "keyup": function(event) {
    $(event.target).val(function(index, value) {
      return value.replace(/\D/g, "")
        .replace(/([0-9])([0-9]{2})$/, '$1,$2')
        .replace(/\B(?=(\d{3})+(?!\d)\.?)/g, ".");
    });
  }
});

function soloNumeros(e){
  key = e.keyCode || e.which;
  tecla = String.fromCharCode(key).toLowerCase();
  letras = "1234567890";
  especiales = "8-37-39-46";

  tecla_especial = false
  for(var i in especiales){
    if(key == especiales[i]){
      tecla_especial = true;
      break;
    }
  }

  if(letras.indexOf(tecla)==-1 && !tecla_especial){
    return false;
  }
}

</script>

@endsection

resources/views/dashboard/Depto/tesoreria_index.blade.php
@extends('templates.master')

@section('css')

<!-- DataTables -->  
<link rel="stylesheet" type="text/css" href="{{asset('public/plugins/datatables/dataTables.bootstrap.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('public/plugins/datatables/prueba/buttons.dataTables.min.css')}}">

<style type="text/css">
table.dataTable tbody td { 
  vertical-align: middle; 
}
table.dataTable thead th { 
  vertical-align: middle; 
}
</style>

@endsection

@section('titulo_modulo', Auth::user()->nombre.' - Bienvenid@')

@section('contenido')
<div class="row" >

  <div class="col-md-12">
    <div class="box box-success">
      <div class="box-body">
          <a class="btn btn-default btn-flat" href="{{route('cuentas_tesoreria.create')}} ">
            <span class="text-success"><i class="fa fa-plus"></i>Agregar Cuentas</span>
          </a>
          <a href='javascript:void(0)' class="btn btn-default pull-right"  id="actualizar-tabla"><i class="fa fa-repeat"></i> Actualizar</a>
          <br /><br />
          <table id="example1" class="table table-bordered table-hover table-striped compact" style="text-align: center; font-size: smaller;">
            <thead >
              <tr style="text-align: center;">
                <th>
                  <input name="select_all" value="1" id="select-all-cuentas" type="checkbox">
                </th>
                <th style="text-align: center;">ID</th>
                <th style="text-align: center;">SEMANA DEL</th> 
                <th style="text-align: center;">AREAS</th>
                <th style="text-align: center;">BENEFICIARIOS</th> 
                <th style="text-align: center;">CONCEPTOS</th>
                <th style="text-align: center;">FECHA TOPE</th>
                <th style="text-align: center;">NRO. ORDEN DE COMPRA</th>
                <th style="text-align: center;">NRO. FACTURA</th>
                <th style="text-align: center;">ESTATUS</th>  
                <th style="text-align: center;">MONTOS PROGRAMADOS</th>
                <th style="text-align: center;">IGTF PROGRAMADOS</th> 
                <th style="text-align: center;">TOTAL PROGRAMADOS</th> 
                <th style="text-align: center;">MONTO PAGADOS</th> 
                <th style="text-align: center;">IGTF PAGADOS</th> 
                <th style="text-align: center;">TOTAL PAGADOS</th> 
                <th style="text-align: center;">VARIACIÓN</th> 
                <th></th> 
              </tr>
            </thead>

            <tfoot>
              <tr>
                <th></th>
                <th style="text-align: center;">ID</th>
                <th style="text-align: center;">SEMANA DEL</th> 
                <th style="text-align: center;">AREAS</th>
                <th style="text-align: center;">BENEFICIARIOS</th> 
                <th style="text-align: center;">CONCEPTOS</th>
                <th style="text-align: center;">FECHA TOPE</th>
                <th style="text-align: center;">NRO. ORDEN DE COMPRA</th>
                <th style="text-align: center;">NRO. FACTURA</th>
                <th style="text-align: center;">ESTATUS</th>  
                <th style="text-align: center;">MONTOS PROGRAMADOS</th>
                <th style="text-align: center;">IGTF PROGRAMADOS</th> 
                <th style="text-align: center;">TOTAL PROGRAMADOS</th> 
                <th style="text-align: center;">MONTO PAGADOS</th> 
                <th style="text-align: center;">IGTF PAGADOS</th> 
                <th style="text-align: center;">TOTAL PAGADOS</th> 
                <th style="text-align: center;">VARIACIÓN</th> 
                <th></th>  
              </tr>
            </tfoot>
          </table>
      </div>
      <div class="box-footer">
        <button class="btn btn-info btn-sm btn-flat" style="width: 100px"  id="btn-aprobar-select"><i class="fa fa-check"></i> APROBAR</button>
        <button class="btn btn-danger btn-sm btn-flat" style="width: 100px" id="btn-rechazar-select"><i class="fa fa-close"></i> RECHAZAR</button>
        <a class="btn btn-success btn-sm btn-flat pull-right" style="width: 100px" href="{{route('cuentas_tesoreria.por_pagar')}} ">
          <i class="fa fa-money"></i> PAGAR
        </a>
      </div><!-- /.box-footer-->
    </div>
  </div>
</div>

@include('dashboard.Depto.cuenta_modal')
  
@endsection

@section('js')

<!-- DataTables -->
<script src="{{asset('public/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/prueba/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/prueba/jszip.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/prueba/buttons.html5.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/prueba/dataTables.colReorder.min.js')}}"></script>

<script type="text/javascript" src="{{asset('public/js/tesoreria.js')}}"></script>

<script type="text/javascript">
$(".numero").on({
  "focus": function(event) {
    $(event.target).select();
  },
  "keyup": function(event) {
    $(event.target).val(function(index, value) {
      return value.replace(/\D/g, "")
        .replace(/([0-9])([0-9]{2})$/, '$1,$2')
        .replace(/\B(?=(\d{3})+(?!\d)\.?)/g, ".");
    });
  }
});
</script>

@endsection